title: NLW2 Proffy Web
description: Durante o evento Next Level Week #2, foi desenvolvido a projeto Proffy, que é uma plataforma de estudos online, conectando alunos com professores para aulas online.
github_username: https://github.com/shyoutarou
theme: jekyll-theme-midnight
